Algoritmo "exercicio8-potencia"
// 
//  
// Descrição   : achar a potência de um número
// Autor(a)    : Derick Campos Silva
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
N1: inteiro
N2: inteiro
elevado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual o primeiro número? ")
leia(N1)
escreva("Qual o segundo número? ")
leia(N2)

elevado <- N1^N2
escreva("O resultado da potência é: ", elevado)

Fimalgoritmo