Algoritmo "exercicio3-antecessor e sucessor"
//  
// Descrição   : ver antecessor e sucessor
// Autor(a)    : Derick Campos Silva
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
n1:inteiro
a: inteiro
s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual é o número? ")
leia(n1)
a <- n1-1
s <- n1+1
escreva("O antecessor é: ", a)
escreva(", O sucessor é: ", s)

Fimalgoritmo