Algoritmo "exercicio7-resto_da_divisao"
// 
//  
// Descrição   : mostrar o resto da divisão de um número por 2
// Autor(a)    : Derick Campos Silva
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
N1: inteiro
divisao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual o número que você deseja calcular? ")
leia(N1)
divisao <- N1/2

escreva("O resto da divisão é: ",divisao)

Fimalgoritmo