Algoritmo "exercicio5-conversao de idade"
// 
//  
// Descrição   : converte anos em dias e meses
// Autor(a)    : Derick Campos Silva (Yasmin)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
idade: inteiro
dia: inteiro
meses: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Quantos anos você tem? ")
leia(idade)
meses <- idade * 12
dia <- idade * 365
escreva("Sua idade em meses é", meses)
escreva(", Sua idade em dias é", dia)

Fimalgoritmo