Algoritmo "exercicio11_aprovado_ou_reprovado"
// 
//  
// Descrição   : checar se você é aprovado ou não com sua média
// Autor(a)    : Derick Campos Silva (yasmin)
// Data atual  : 26/02/2026
Var
// Seção de Declarações das variáveis 
media:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Qual é a nota do aluno?")
leia (media)

se (media>=7) entao
escreva ("Aprovado.")
senao
escreva ("Reprovado.")
fimse

Fimalgoritmo