Algoritmo "exercicio9_par_ou_impar"
// 
//  
// Descrição   : descobrir se um número é par ou ímpar
// Autor(a)    : Derick Campos Silva (yasmin)
// Data atual  : 26/02/2026
Var
// Seção de Declarações das variáveis 
num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual é o seu número?")
leia(num)

se (num%2=0)entao
escreva ("Seu número é par!")
senao
escreva ("Seu número é ímpar!")
fimse

Fimalgoritmo